[package]
name = "pcf8563"
version = "0.1.0"
edition = "2021"

[dependencies]
bit_field = "0.10.2"
defmt = { version = "0.3.8", optional = true }
embedded-hal = "1.0.0"
num_enum = { version = "0.7.3", default-features = false }

[features]
defmt = ["dep:defmt", "embedded-hal/defmt-03"]
